### ISSUE TITLE
How to use Quill-task-list with ngQuill

### ISSUE THREAD

**Issue by hantsy** [koffeinfrei/quill-task-list#3]
Hi @koffeinfrei 

I am trying to integrate this Quill extension into my project which is based on AngularJS/ES6/Webpack, I also used https://github.com/KillerCodeMonkey/ng-quill. 

When I imported quill-task-list like this and use ngQuillConfig to set the tasklist. 

```
import  './quill-task-list';
```

**It will report the tasklist is not registered.**

It is possible to use this tools as a standalone ES 6 module?

Thanks.

**Comment by koffeinfrei** [comment]
I don't know how to properly configure `ng-quill`.
Can you provide more code on how exactly your configuration looks like? Is the import statement executed before the configuration?

**Comment by hantsy** [comment]
@koffeinfrei  Hi, Thanks for your reply.

Yeah, of course I can provide the configure code piece there.  I copied the codes(renamed it to *js* extension) in our project.  And in `angular.config` section, I used it like this.

```
import  './quill-tasklist';
import './quill-tasklist.styl';

//
// omitted some codes here.
  ngQuillConfigProvider.set(
    {
      toolbar: [
        ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
        ['blockquote', 'code-block'],

        [{ 'header': 1 }, { 'header': 2 }],               // custom button values
        [{ 'list': 'ordered' }, { 'list': 'bullet' }],
        [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
        [{ 'indent': '-1' }, { 'indent': '+1' }],          // outdent/indent
        [{ 'direction': 'rtl' }],                         // text direction

        [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

        [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
        [{ 'font': [] }],
       // [ 'task-list' ],
        [{ 'align': [] }],

        ['clean'],                                         // remove formatting button

        ['link', 'image', 'video']                         // link and image, video
      ],
      //'task-list': true
    }
  );
```

`ngQuillConfigProvider` is a standard Angular provider, and use for configure the Quill for ng-quill component/directive.

The ngQuill source code can be found this.

https://github.com/KillerCodeMonkey/ng-quill/blob/develop/src/ng-quill.js

When I tried to add tasklist there, used the ngQuill editor, there is an empty placeholder in the position of `tasklist`, did not display the toolbar icon instead, and in the Chrome console log, it will complain *tasklist is not registered*.  I am afraid he **import** clause does not execute the file there.

**Comment by koffeinfrei** [comment]
Is your import statement actually loading the script? Can you add some debug statement (`alert` or `console.debug` or something similar) to `quill-tasklist` to see if the import actually is correct?

**Comment by hantsy** [comment]
@koffeinfrei  I have tried to add some log in quill-tasklist source code, it is executed.

**Comment by koffeinfrei** [comment]
Did you manage to figure this out?

I'm guessing that the import of my plugin is too early, and the `ng-quill` instantiates the actual `Quill` instance later. My plugin should be executed only after the actual `Quill`gets instantiated.

Can you try to prepend `import  'quill';` to the `import  './quill-tasklist';` statement?

**Comment by koffeinfrei** [comment]
I'll close this due to inactivity. Feel free to reopen this when you get back to this.
