### ISSUE TITLE
Quill is not defined

### ISSUE THREAD

**Issue by xueqiliu** [koffeinfrei/quill-task-list#5]
import Quill from 'quill'
import 'quill-task-list/task_list.js'
`Uncaught ReferenceError: Quill is not defined`
![image](https://user-images.githubusercontent.com/8528958/71575945-c0694780-2b29-11ea-8c52-7cde10afb18f.png)
I need import Quill in source code for work
```
// import Quill from 'quill'
const List = Quill.import('formats/list');
const ListItem = Quill.import('formats/list/item');
const Parchment = Quill.import('parchment');
.....
```
Is there any other way？

**Comment by koffeinfrei** [comment]
In a node.js / module context you can use https://github.com/koffeinfrei/quill-task-list/blob/master/task_list_node.js. This is also [what I'm doing in Mykonote](https://github.com/panter/mykonote/blob/master/client/src/NoteForm.js#L4) in a React component.

Is this what you're looking for?

**Comment by koffeinfrei** [comment]
> Is there any other way？

No, you need to import Quill for the plugin to work. Either by requiring it to be globally available or by having a module import (see my above comment for this).
