### ISSUE TITLE
Obselete library

### ISSUE THREAD

**Issue by ClementCariou** [koffeinfrei/quill-task-list#8]
I just want to point out that this library is obselete since Quill js now supports takslists natively :
```js
const modules = {
  toolbar: [
    { list: "check" }
  ]
};
```
Maybe this information could be written in the Readme.

**Comment by koffeinfrei** [comment]
The check-list implementation is not officially released yet. But you're right, it could be useful to mention that. I added some info in the README in https://github.com/koffeinfrei/quill-task-list/commit/b693c5ee6af3c1c69d0c9f07da3d281e75bdd930 though.
